name: Update App Versions

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run update versions script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x .github/scripts/update_versions.sh
          bash .github/scripts/update_versions.sh

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Generate changelog
        if: env.changes == 'true'
        run: |
          echo "## 🆕 Updated App Versions" > changelog.md
          echo "" >> changelog.md
          git diff --unified=0 | grep '^+' | grep 'version=' | sed 's/^+//' >> changelog.md
          echo "" >> changelog.md
          echo "📌 This PR updates the app versions with the latest releases from GitHub." >> changelog.md

      - name: Create Pull Request
        if: env.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-app-versions
          delete-branch: true
          title: "🔄 Update App Versions"
          body-file: changelog.md
          labels: "dependencies, automated"
          commit-message: "Update app versions with latest releases from GitHub"